name: 'procheck'
author: 'Hyperjump'
description: 'A project convention checker'
inputs:
  repository:
    required: true
    description: 'Configs repository'
  configPath:
    required: true
    description: 'Configs path'
  token:
    required: false,
    description: 'Github PAT token to fetch contents from a private repository'
runs:
  using: 'node12'
  main: 'dist/index.js'
